## cal calculator ##
a=int(input("Enter a number1: "))
b=int(input("Enter a number2: "))
print("Addition is: ", a+b)
print("Subtraction is: ", a-b)
print("Multiplication is: ", a*b)
print("Division is: ", a/b)
print("Modulus is: ", a%b)
print("Exponentiation is: ", a**b)
print("Floor Division is: ", a//b)
print("Square root of a is: ", a**0.5)
print("Square root of b is: ", b**0.5)
print("Square root of a+b is: ", (a+b)**0.5)
print("Square root of a-b is: ", (a-b)**0.5 if a >= b else "Undefined (a < b)")
print("Square root of a*b is: ", (a*b)**0.5)
print("Square root of a/b is: ", (a/b)**0.5 if b != 0 else "Undefined (b = 0)")
